(in-package #:clx-xim)

(defgeneric -clx-xim-handle-message- (clx-xim hdr data type)
  (:documentation "doc"))

(defmethod -clx-xim-handle-message- (clx-xim hdr data (type (eql *clx-xim-connect-reply*)))
  (format t "*clx-xim-connect-reply* :~A~%" *clx-xim-connect-reply*)
  ;; (unless (eq (open-state clx-xim) :xim-open-wait-open-reply)
  ;;   (return-from -clx-xim-handle-message- NIL))
  )

(defmethod -clx-xim-handle-message- (clx-xim hdr data (type (eql *clx-xim-open-reply*)))
  (unless (eq (open-state clx-xim) :xim-open-wait-open-reply)
    (return-from -clx-xim-handle-message- NIL))
  (format t "*clx-xim-open-reply* :~A~%" *clx-xim-open-reply*)
  ;; (format t "~A" data)
  (print (length data))
  (let ((frame (-clx-xim-read-frame- data :clx-im-open-reply-fr)))
    ;; (format t "~A~%" frame)
    ))
