(in-package #:ximproth)

(defparameter *clx-xim-connect* 1)
(defparameter *clx-xim-connect-reply* 2)
(defparameter *clx-xim-disconnect* 3)
(defparameter *clx-xim-disconnect-reply* 4)

(defparameter *clx-xim-auth-required* 10)
(defparameter *clx-xim-auth-reply* 11)
(defparameter *clx-xim-auth-next* 12)
(defparameter *clx-xim-auth-setup* 13)
(defparameter *clx-xim-auth-ng* 14)

(defparameter *clx-xim-error* 20)

(defparameter *clx-xim-open* 30)
(defparameter *clx-xim-open-reply* 31)
(defparameter *clx-xim-close* 32)
(defparameter *clx-xim-close-reply* 33)
(defparameter *clx-xim-register-triggerkeys* 34)
(defparameter *clx-xim-trigger-notify* 35)
(defparameter *clx-xim-trigger-notify-reply* 36)
(defparameter *clx-xim-set-event-mask* 37)
(defparameter *clx-xim-encoding-negotiation* 38)
(defparameter *clx-xim-encoding-negotiation-reply* 39)

(defparameter *clx-xim-query-extension* 40)
(defparameter *clx-xim-query-extension-reply* 41)
(defparameter *clx-xim-set-im-values* 42)
(defparameter *clx-xim-set-im-values-reply* 43)
(defparameter *clx-xim-get-im-values* 44)
(defparameter *clx-xim-get-im-values-reply* 45)

(defparameter *clx-xim-create-ic* 50)
(defparameter *clx-xim-create-ic-reply* 51)
(defparameter *clx-xim-destroy-ic* 52)
(defparameter *clx-xim-destroy-ic-reply* 53)
(defparameter *clx-xim-set-ic-values* 54)
(defparameter *clx-xim-set-ic-values-reply* 55)
(defparameter *clx-xim-get-ic-values* 56)
(defparameter *clx-xim-get-ic-values-reply* 57)
(defparameter *clx-xim-set-ic-focus* 58)
(defparameter *clx-xim-unset-ic-focus* 59)

(defparameter *clx-xim-forward-event* 60)
(defparameter *clx-xim-sync* 61)
(defparameter *clx-xim-sync-reply* 62)
(defparameter *clx-xim-commit* 63)
(defparameter *clx-xim-reset-ic* 64)
(defparameter *clx-xim-reset-ic-reply* 65)

(defparameter *clx-xim-geometry* 70)
(defparameter *clx-xim-str-conversion* 71)
(defparameter *clx-xim-str-conversion-reply* 72)
(defparameter *clx-xim-preedit-start* 73)
(defparameter *clx-xim-preedit-start-reply* 74)
(defparameter *clx-xim-preedit-draw* 75)
(defparameter *clx-xim-preedit-caret* 76)
(defparameter *clx-xim-preedit-caret-reply* 77)
(defparameter *clx-xim-preedit-done* 78)
(defparameter *clx-xim-status-start* 79)
(defparameter *clx-xim-status-draw* 80)
(defparameter *clx-xim-status-done* 81)


;; Minor Protocol Number for Extension Protocol
(defparameter *clx-xim-extension* 128)
(defparameter *clx-xim-ext-set-event-mask* #x30)
(defparameter *clx-xim-ext-forward-keyevent* #x32)
(defparameter *clx-xim-ext-move* #x33)


(defparameter *clx-xim-xnquery-inputstyle* "queryInputstyle")
(defparameter *clx-xim-xnclient-window* "clientWindow")
(defparameter *clx-xim-xninput-style* "inputStyle")
(defparameter *clx-xim-xnfocus-window* "focusWindow")
(defparameter *clx-xim-xnfilter-events* "filterEvents")
(defparameter *clx-xim-xnpreedit-attributes* "preeditAttributes")
(defparameter *clx-xim-xnstatus-attributes* "statusAttributes")
(defparameter *clx-xim-xnarea* "area")
(defparameter *clx-xim-xnarea-needed* "areaNeeded")
(defparameter *clx-xim-xnspot-location* "spotLocation")
(defparameter *clx-xim-xncolormap* "colorMap")
(defparameter *clx-xim-xnstd-colormap* "stdColorMap")
(defparameter *clx-xim-xnforeground* "foreground")
(defparameter *clx-xim-xnbackground* "background")
(defparameter *clx-xim-xnbackground-pixmap* "backgroundPixmap")
(defparameter *clx-xim-xnfont-set* "fontSet")
(defparameter *clx-xim-xnline-space* "lineSpace")
(defparameter *clx-xim-xnseparatorof-nested-list* "separatorofNestedlist")


;; values for the type of XIMATTR & XICATTR
(defparameter *ximtype-separatorofnestedlist* 0)
(defparameter *ximtype-card8* 1)
(defparameter *ximtype-card16* 2)
(defparameter *ximtype-card32* 3)
(defparameter *ximtype-string8* 4)
(defparameter *ximtype-window* 5)
(defparameter *ximtype-ximstyles* 10)
(defparameter *ximtype-xrectangle* 11)
(defparameter *ximtype-xpoint* 12)
(defparameter *ximtype-xfontset* 13)
(defparameter *ximtype-ximoptions* 14)
(defparameter *ximtype-ximhotkeytriggers* 15)
(defparameter *ximtype-ximhotkeystate* 16)
(defparameter *ximtype-ximstringconversion* 17)
(defparameter *ximtype-ximvalueslist* 18)
(defparameter *ximtype-nest* #x7fff)


;; (defun clx-im-ic-attr-size (type)
;;   (cond ((or (eq type *ximtype-card32*)
;; 	     (eq type *ximtype-window*))
;; 	 4)
;; 	((eq type *ximtype-xrectangle*)
;; 	 8)
;; 	((eq type *ximtype-xpoint*)
;; 	 4)))

(defparameter *clx-im-preeditarea* #x0001)
(defparameter *clx-im-preeditcallbacks* #x0002)
(defparameter *clx-im-preeditposition* #x0004)
(defparameter *clx-im-preeditnothing* #x0008)
(defparameter *clx-im-preeditnone* #x0010)
(defparameter *clx-im-statusarea* #x0100)
(defparameter *clx-im-statuscallbacks* #x0200)
(defparameter *clx-im-statusnothing* #x0400)
(defparameter *clx-im-statusnone* #x0800)

(defparameter *clx-xim-synchronous* 1)
(defparameter *clx-xim-lookup-chars*  2)
(defparameter *clx-xim-lookup-keysym*  4)
(defparameter *clx-xim-lookup-both*  (logior *clx-xim-lookup-chars* *clx-xim-lookup-keysym*))
